// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS_Assesment.Models;

#nullable disable

namespace TMS_Assesment.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    partial class TmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS_Assesment.Models.Maintenance", b =>
                {
                    b.Property<int?>("Maintenance_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Maintenance_Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Maintenance_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Maintenance_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maintenance_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Vehicle_Id")
                        .HasColumnType("int");

                    b.HasKey("Maintenance_Id");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("MaintenanceActivities");
                });

            modelBuilder.Entity("TMS_Assesment.Models.Vehicle", b =>
                {
                    b.Property<int?>("Vehicle_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Vehicle_Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vehicle_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle_Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TMS_Assesment.Models.Maintenance", b =>
                {
                    b.HasOne("TMS_Assesment.Models.Vehicle", "Vehicle")
                        .WithMany("Maintenances")
                        .HasForeignKey("Vehicle_Id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TMS_Assesment.Models.Vehicle", b =>
                {
                    b.Navigation("Maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
